//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkaneSystems.Arkane.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArkaneSystems.Arkane.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a System.Exception or a type derived from System.Exception..
        /// </summary>
        internal static string CallMeMaybeAttribute_CallMeMaybeAttribute_MustBeExceptionType {
            get {
                return ResourceManager.GetString("CallMeMaybeAttribute_CallMeMaybeAttribute_MustBeExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened which cannot happen..
        /// </summary>
        internal static string CannotHappenException_CannotHappenException_SomethingHappened {
            get {
                return ResourceManager.GetString("CannotHappenException_CannotHappenException_SomethingHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred on another thread and has been marshaled into this wrapper: {0}..
        /// </summary>
        internal static string CrossThreadException_CrossThreadException_ExceptionHasBeenMarshaled {
            get {
                return ResourceManager.GetString("CrossThreadException_CrossThreadException_ExceptionHasBeenMarshaled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} object was not disposed. You should call Dispose() on this {1} instead of letting it be finalized..
        /// </summary>
        internal static string DisposerBase__DisposerBase_ObjectWasNotDisposed {
            get {
                return ResourceManager.GetString("DisposerBase_~DisposerBase_ObjectWasNotDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disposer: Can&apos;t be a method with parameters..
        /// </summary>
        internal static string DisposerByReflection_DisposerByReflection_CantBeMethodWithParameters {
            get {
                return ResourceManager.GetString("DisposerByReflection_DisposerByReflection_CantBeMethodWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disposer: Can&apos;t be a static method..
        /// </summary>
        internal static string DisposerByReflection_DisposerByReflection_CantBeStaticMethod {
            get {
                return ResourceManager.GetString("DisposerByReflection_DisposerByReflection_CantBeStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disposer: Can&apos;t be a method with unassigned generic type parameters..
        /// </summary>
        internal static string DisposerByReflection_DisposerByReflection_disposer_CantBeMethodWithUnassignedTypeParams {
            get {
                return ResourceManager.GetString("DisposerByReflection_DisposerByReflection_disposer_CantBeMethodWithUnassignedType" +
                        "Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disposer: Object does not have a public, parameterless {0} instance method..
        /// </summary>
        internal static string DisposerByReflection_GetPublicParameterlessInstanceMethod_NoPublicParamlessInstanceMethod {
            get {
                return ResourceManager.GetString("DisposerByReflection_GetPublicParameterlessInstanceMethod_NoPublicParamlessInstan" +
                        "ceMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call this method for a non-flags enum..
        /// </summary>
        internal static string Enums_GetUsedBits_CannotCallForNonFlags {
            get {
                return ResourceManager.GetString("Enums_GetUsedBits_CannotCallForNonFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown enumeration value name..
        /// </summary>
        internal static string Enums_ParseName_UnknownValueName {
            get {
                return ResourceManager.GetString("Enums_ParseName_UnknownValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate log message..
        /// </summary>
        internal static string LoggerExecutionWrapper_FailedToGenerateLogMessage {
            get {
                return ResourceManager.GetString("LoggerExecutionWrapper_FailedToGenerateLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred resolving a log provider. Logging for this assembly {0} is disabled. {1}.
        /// </summary>
        internal static string LogProvider_ForceResolveLogProvider_ExceptionResolvingLogProvider {
            get {
                return ResourceManager.GetString("LogProvider_ForceResolveLogProvider_ExceptionResolvingLogProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to log due to problem initializing the log provider. See inner exception for details..
        /// </summary>
        internal static string LogProviderBase_ErrorInitializingProvider_ProblemInitializingLogProvider {
            get {
                return ResourceManager.GetString("LogProviderBase_ErrorInitializingProvider_ProblemInitializingLogProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to dispose the same Memento twice..
        /// </summary>
        internal static string Memento_Dispose_AttemptedSecondDisposal {
            get {
                return ResourceManager.GetString("Memento_Dispose_AttemptedSecondDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code in this method should have been replaced at build time by the Packer. If you see this, it&apos;s probably because you didn&apos;t configure Packer with an assembly-wide attribute..
        /// </summary>
        internal static string PackerUtility_Initialize_CodeNotReplaced {
            get {
                return ResourceManager.GetString("PackerUtility_Initialize_CodeNotReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PostCompile aspect cannot be applied to constructors/destructors..
        /// </summary>
        internal static string PostCompileAttribute_CompileTimeValidate_CannotApplyToConstructorsDestructors {
            get {
                return ResourceManager.GetString("PostCompileAttribute_CompileTimeValidate_CannotApplyToConstructorsDestructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PostCompile aspect can only be applied to methods without parameters..
        /// </summary>
        internal static string PostCompileAttribute_CompileTimeValidate_CanOnlyApplyToParameterless {
            get {
                return ResourceManager.GetString("PostCompileAttribute_CompileTimeValidate_CanOnlyApplyToParameterless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PostCompile aspect can only be applied to static methods..
        /// </summary>
        internal static string PostCompileAttribute_CompileTimeValidate_CanOnlyApplyToStaticMethods {
            get {
                return ResourceManager.GetString("PostCompileAttribute_CompileTimeValidate_CanOnlyApplyToStaticMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PostCompile aspect can only be applied to methods returning void..
        /// </summary>
        internal static string PostCompileAttribute_CompileTimeValidate_CanOnlyApplyToVoidReturn {
            get {
                return ResourceManager.GetString("PostCompileAttribute_CompileTimeValidate_CanOnlyApplyToVoidReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last post-compile run failed at {0}: {1}..
        /// </summary>
        internal static string PostCompileAttribute_CompileTimeValidate_LastPostCompileRunFailed {
            get {
                return ResourceManager.GetString("PostCompileAttribute_CompileTimeValidate_LastPostCompileRunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last post-compile run succeeded at {0}..
        /// </summary>
        internal static string PostCompileAttribute_CompileTimeValidate_LastPostCompileRunSucceeded {
            get {
                return ResourceManager.GetString("PostCompileAttribute_CompileTimeValidate_LastPostCompileRunSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Serilog.ILogger was not found..
        /// </summary>
        internal static string SerilogLogger_Initialize_ILoggerNotFound {
            get {
                return ResourceManager.GetString("SerilogLogger_Initialize_ILoggerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Serilog.Events.LogEventLevel was not found..
        /// </summary>
        internal static string SerilogLogger_Initialize_LogLevelEventTypeNotFound {
            get {
                return ResourceManager.GetString("SerilogLogger_Initialize_LogLevelEventTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serilog Log type not found..
        /// </summary>
        internal static string SerilogLogProvider_GetForContextMethodCall_LogNotFound {
            get {
                return ResourceManager.GetString("SerilogLogProvider_GetForContextMethodCall_LogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serilog LogContext type not found..
        /// </summary>
        internal static string SerilogLogProvider_GetPushProperty_LogContextNotFound {
            get {
                return ResourceManager.GetString("SerilogLogProvider_GetPushProperty_LogContextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serilog.Log not found..
        /// </summary>
        internal static string SerilogLogProvider_SerilogLogProvider_LogNotFound {
            get {
                return ResourceManager.GetString("SerilogLogProvider_SerilogLogProvider_LogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous Instance property..
        /// </summary>
        internal static string SingletonConstraintAttribute_ValidateCode_AmbiguousInstanceProperty {
            get {
                return ResourceManager.GetString("SingletonConstraintAttribute_ValidateCode_AmbiguousInstanceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} type does not have &apos;private static readonly Lazy&lt;{0}&gt; Lazy = new Lazy&lt;{0}&gt; (() =&gt; new {0} ());&apos;..
        /// </summary>
        internal static string SingletonConstraintAttribute_ValidateCode_NoInstanceCreationMethod {
            get {
                return ResourceManager.GetString("SingletonConstraintAttribute_ValidateCode_NoInstanceCreationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} type does not have &apos;public static {0} Instance =&gt; {0}.Lazy.Value&apos;..
        /// </summary>
        internal static string SingletonConstraintAttribute_ValidateCode_NoInstanceProperty {
            get {
                return ResourceManager.GetString("SingletonConstraintAttribute_ValidateCode_NoInstanceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} type does not have a single, parameterless private constructor..
        /// </summary>
        internal static string SingletonConstraintAttribute_ValidateCode_NoPrivateConstructor {
            get {
                return ResourceManager.GetString("SingletonConstraintAttribute_ValidateCode_NoPrivateConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringManipulationAttribute can only be used on a string..
        /// </summary>
        internal static string StringManipulationAttribute_CompileTimeValidate_CanOnlyBeUsedOnString {
            get {
                return ResourceManager.GetString("StringManipulationAttribute_CompileTimeValidate_CanOnlyBeUsedOnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null..
        /// </summary>
        internal static string StringManipulationAttribute_ConvertString_CannotBeNull {
            get {
                return ResourceManager.GetString("StringManipulationAttribute_ConvertString_CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality must be implemented by a subclass of this base class..
        /// </summary>
        internal static string SubclassResponsibilityException_SubclassResponsibilityException_MustImplementInSubclass {
            get {
                return ResourceManager.GetString("SubclassResponsibilityException_SubclassResponsibilityException_MustImplementInSu" +
                        "bclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}: initiated transaction {2}..
        /// </summary>
        internal static string TransactionAttribute_OnEntry_InitiatedTransaction {
            get {
                return ResourceManager.GetString("TransactionAttribute_OnEntry_InitiatedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}: rolled back transaction {2} on exception..
        /// </summary>
        internal static string TransactionAttribute_OnException_RolledBackTransaction {
            get {
                return ResourceManager.GetString("TransactionAttribute_OnException_RolledBackTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}: committed transaction {2}..
        /// </summary>
        internal static string TransactionAttribute_OnSuccess_CommittedTransaction {
            get {
                return ResourceManager.GetString("TransactionAttribute_OnSuccess_CommittedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid type argument was specified..
        /// </summary>
        internal static string TypeArgumentException_TypeArgumentException_InvalidTypeArgument {
            get {
                return ResourceManager.GetString("TypeArgumentException_TypeArgumentException_InvalidTypeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subclasses of {1} ({0}) cannot be sealed..
        /// </summary>
        internal static string UnsealableConstraintAttribute_ValidateCode_SubclassesCannotBeSealed {
            get {
                return ResourceManager.GetString("UnsealableConstraintAttribute_ValidateCode_SubclassesCannotBeSealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinels cannot be identical..
        /// </summary>
        internal static string ας_System_BetweenSentinels_SentinelsCannotBeIdentical {
            get {
                return ResourceManager.GetString("ας_System_BetweenSentinels_SentinelsCannotBeIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call this method for a non-flags enum..
        /// </summary>
        internal static string ας_System_CannotCallForNonFlagsEnum {
            get {
                return ResourceManager.GetString("ας_System_CannotCallForNonFlagsEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be less than the length of the string..
        /// </summary>
        internal static string ας_System_Left_LengthMustBeLess {
            get {
                return ResourceManager.GetString("ας_System_Left_LengthMustBeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End index must be &gt;= start index..
        /// </summary>
        internal static string ας_System_SubstringByRange_EndIndexMustBePastStartIndex {
            get {
                return ResourceManager.GetString("ας_System_SubstringByRange_EndIndexMustBePastStartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chopSize &gt;= @this.Length.
        /// </summary>
        internal static string ας_System_Text_Chop_ChopLongerThanString {
            get {
                return ResourceManager.GetString("ας_System_Text_Chop_ChopLongerThanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null IDisposable passed to TryDispose()..
        /// </summary>
        internal static string ας_System_TryDispose_NullIDisposablePassedToTryDispose {
            get {
                return ResourceManager.GetString("ας_System_TryDispose_NullIDisposablePassedToTryDispose", resourceCulture);
            }
        }
    }
}
