//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkaneSystems.Arkane.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArkaneSystems.Arkane.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate log message..
        /// </summary>
        internal static string LoggerExecutionWrapper_FailedToGenerateLogMessage {
            get {
                return ResourceManager.GetString("LoggerExecutionWrapper_FailedToGenerateLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred resolving a log provider. Logging for this assembly {0} is disabled. {1}.
        /// </summary>
        internal static string LogProvider_ForceResolveLogProvider_ExceptionResolvingLogProvider {
            get {
                return ResourceManager.GetString("LogProvider_ForceResolveLogProvider_ExceptionResolvingLogProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to log due to problem initializing the log provider. See inner exception for details..
        /// </summary>
        internal static string LogProviderBase_ErrorInitializingProvider_ProblemInitializingLogProvider {
            get {
                return ResourceManager.GetString("LogProviderBase_ErrorInitializingProvider_ProblemInitializingLogProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Serilog.ILogger was not found..
        /// </summary>
        internal static string SerilogLogger_Initialize_ILoggerNotFound {
            get {
                return ResourceManager.GetString("SerilogLogger_Initialize_ILoggerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Serilog.Events.LogEventLevel was not found..
        /// </summary>
        internal static string SerilogLogger_Initialize_LogLevelEventTypeNotFound {
            get {
                return ResourceManager.GetString("SerilogLogger_Initialize_LogLevelEventTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serilog Log type not found..
        /// </summary>
        internal static string SerilogLogProvider_GetForContextMethodCall_LogNotFound {
            get {
                return ResourceManager.GetString("SerilogLogProvider_GetForContextMethodCall_LogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serilog LogContext type not found..
        /// </summary>
        internal static string SerilogLogProvider_GetPushProperty_LogContextNotFound {
            get {
                return ResourceManager.GetString("SerilogLogProvider_GetPushProperty_LogContextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serilog.Log not found..
        /// </summary>
        internal static string SerilogLogProvider_SerilogLogProvider_LogNotFound {
            get {
                return ResourceManager.GetString("SerilogLogProvider_SerilogLogProvider_LogNotFound", resourceCulture);
            }
        }
    }
}
