//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkaneSystems.Arkane.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArkaneSystems.Arkane.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF entity type {0} is missing the [Key] attribute from the Id property..
        /// </summary>
        internal static string EntityConstraintAttribute_ValidateCode_EntityIdMissingKeyAttribute {
            get {
                return ResourceManager.GetString("EntityConstraintAttribute_ValidateCode_EntityIdMissingKeyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF entity type {0} is missing the [Required] attribute from the Id property..
        /// </summary>
        internal static string EntityConstraintAttribute_ValidateCode_EntityIdMissingRequiredAttribute {
            get {
                return ResourceManager.GetString("EntityConstraintAttribute_ValidateCode_EntityIdMissingRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF entity type {0} cannot be sealed or static..
        /// </summary>
        internal static string EntityConstraintAttribute_ValidateCode_EntityTypeCannotBeSealedOrStatic {
            get {
                return ResourceManager.GetString("EntityConstraintAttribute_ValidateCode_EntityTypeCannotBeSealedOrStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF entity type {0} is missing the property &apos;public int Id {{ get; set; }}&apos;..
        /// </summary>
        internal static string EntityConstraintAttribute_ValidateCode_EntityTypeMissingId {
            get {
                return ResourceManager.GetString("EntityConstraintAttribute_ValidateCode_EntityTypeMissingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF entity type {0} is missing the [DatabaseGenerated (DatabaseGeneratedOption.Identity)] attribute from the Id property, or the DatabaseGeneratedOption is incorrect..
        /// </summary>
        internal static string EntityConstraintAttribute_ValidateCode_EntityTypeMissingIncorrectDatabaseGenerated {
            get {
                return ResourceManager.GetString("EntityConstraintAttribute_ValidateCode_EntityTypeMissingIncorrectDatabaseGenerate" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF entity type {0} is missing the property &apos;public byte[] Version {{ get; set; }}&apos;..
        /// </summary>
        internal static string EntityConstraintAttribute_ValidateCode_EntityTypeMissingVersion {
            get {
                return ResourceManager.GetString("EntityConstraintAttribute_ValidateCode_EntityTypeMissingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF entity type {0} is not public..
        /// </summary>
        internal static string EntityConstraintAttribute_ValidateCode_EntityTypeNotPublic {
            get {
                return ResourceManager.GetString("EntityConstraintAttribute_ValidateCode_EntityTypeNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF entity type {0} is missing the [Timestamp] attribute from the Version property..
        /// </summary>
        internal static string EntityConstraintAttribute_ValidateCode_EntityVersionMissingTimestamp {
            get {
                return ResourceManager.GetString("EntityConstraintAttribute_ValidateCode_EntityVersionMissingTimestamp", resourceCulture);
            }
        }
    }
}
